apiVersion: argoproj.io/v1alpha1
kind: AppProject
  metadata:  
    name: {{ .Values.app.namespace }}  
  spec:  
    destinations:  
    - namespace: {{ .Values.app.namespace }}    
      server: https://kubernetes.default.svc  
    sourceRepos:  
    - '*'