apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: deploy-config-policy
spec:
  workspaces:
  - name: source
    description: "The workspace containing source code"
  steps:
    - workingDir: "/workspace/source"
      name: retrieve-api-ids
      image: amazon/aws-cli
      script: |
        #!/usr/bin/env bash
        echo "================="
        echo "Get JWT Secret" 
        echo "================="

	      # AWS CLI Command to retrieve secret would go here
        jwt_secret=$(echo "dummyvalue")
        echo "export jwt_secret=${jwt_secret}" >> variables.export

    - script: |
        #!/usr/bin/env bash
        echo "==============================================="
        echo "Deploy chart with default policy for OPA Agent" 
        echo "==============================================="
                
        # source file with environment variables
        source variables.export

        [ -n "$jwt_secret" ] || { echo "jwt_secret was not found"; exit 1; }
       
        helmParameters="--set jwtSecret='${jwt_secret}'"

        echo "Deploying helm release: policy-chart with arguments: ${helmFile}"
        # Run Helm Command
        helm upgrade -i policy-chart ./iac/tekton/policy-chart ${helmFile} ${helmParameters}

      image: rhel8/support-tools
      name: install-helm-chart
      workingDir: "/workspace/source"
