apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-aws-secret
spec:
  workspaces:
  - name: source
    description: "The workspace containing source code"
  params:
    - name: secret_name
      description: "The AWS secret name"
      default: "jwtSecret"
  results:
    - name: secret_value
      description: The secret value      
  steps:
    - workingDir: "/workspace/source"
      name: retrieve-api-ids
      image: amazon/aws-cli
      script: |
        #!/usr/bin/env bash
        echo "================="
        echo "Get JWT Secret" 
        echo "================="

        # AWS CLI Command to retrieve secret would go here
        secret=$(echo "dummyvalue")
        echo "${secret}" | tee $(results.secret-value.path)

      image: registry.redhat.io/rhel8/support-tools:8.7
      name: install-helm-chart
      workingDir: "/workspace/source"
