apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-secret
spec:
  workspaces:
  - name: source
    description: "The workspace containing source code"
  params:
    - name: secret_name
      description: "The secret name"
      default: "jwtSecret"
  results:
    - name: secret_value
      description: The secret value      
  steps:
    - workingDir: "/workspace/source"
      name: retrieve-secret
      image: mcr.microsoft.com/azure-cli
      script: |
        #!/usr/bin/env bash
        echo "================="
        echo "Get Secret" 
        echo "================="

        # CLI Command to retrieve secret would go here
        secret=$(echo -n "dummyvalue")
        echo -n "$secret" > $(results.secret_value.path)
        echo "SUCCESS"
