apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: configure-opa
spec:
  params:
    - default: 'https://github.com/yortch/opa-demo.git'
      name: git-url
      type: string
    - default: tekton
      name: git-ref
      type: string
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-ref)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: crtFileName
          value: ca-bundle.crt
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: deploy-config-policy
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: deploy-config-policy
      workspaces:
        - name: source
          workspace: source
        - name: secrets
          workspace: source
  workspaces:
    - name: source
