apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: configure-opa
spec:
  params:
    - default: 'https://github.com/yortch/opa-demo.git'
      name: git-url
      type: string
    - default: tekton
      name: git-ref
      type: string
    - default: {{ include "opa-chart.fullname" . }}
      name: deployment-name
      type: string      
  tasks:
    - name: git-clone
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-ref)
        - name: submodules
          value: 'true'
        - name: depth
          value: '1'
        - name: sslVerify
          value: 'true'
        - name: deleteExisting
          value: 'true'
        - name: verbose
          value: 'true'
        - name: gitInitImage
          value: >-
            registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:a538c423e7a11aae6ae582a411fdb090936458075f99af4ce5add038bb6983e8
        - name: userHome
          value: /tekton/home
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: source
    - name: get-jwt-secret
      runAfter:
        - git-clone
      taskRef:
        kind: Task
        name: get-aws-secret
      workspaces:
        - name: source
          workspace: source 
    - name: install-policy-chart
      runAfter:
        - get-jwt-secret
      taskRef:
        kind: ClusterTask
        name: helm-upgrade-from-source
      params:
        - name: charts_dir
          value: iac/tekton/policy-chart
        - name: release_version
          value: v1.0.0
        - name: release_name
          value: policy-chart
        - name: values_file
          value: values.yaml  
        - name: overwrite_values
          value: jwtSecret=$(tasks.get-jwt-secret.results.secret_value),appname={{ .Release.Name }},clientId={{ .Values.opa.clientId }}
        - name: helm_image
          value: >-
            docker.io/lachlanevenson/k8s-helm@sha256:5c792f29950b388de24e7448d378881f68b3df73a7b30769a6aa861061fd08ae
      workspaces:
        - name: source
          workspace: source 
    - name: restart
      params:
        - name: SCRIPT
          value: oc rollout restart deployment $(params.deployment-name)
        - name: VERSION
          value: latest
      runAfter:
        - install-policy-chart
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: source
