kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "opa-chart.fullname" . }}
  labels:
    {{- include "opa-chart.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "opa-chart.fullname" . }}
  port:
    targetPort: http